= Asciidoctor
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>; Sarah White <https://github.com/graphitefriction[@graphitefriction]>
// settings:
:idprefix:
:idseparator: -
:source-language: ruby
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Variables:
:release-version: 2.0.16
// URLs:
:url-org: https://github.com/asciidoctor
:url-repo: {url-org}/asciidoctor
:url-asciidoctorj: {url-org}/asciidoctorj
:url-asciidoctorjs: {url-org}/asciidoctor.js
:url-gradle-plugin: {url-org}/asciidoctor-gradle-plugin
:url-maven-plugin: {url-org}/asciidoctor-maven-plugin
:url-asciidoclet: {url-org}/asciidoclet
:url-project: https://asciidoctor.org
ifdef::env-site[:url-project: link:]
:url-docs: https://docs.asciidoctor.org
:url-news: {url-project}/news
:url-manpage: {url-project}/man/asciidoctor
:url-issues: {url-repo}/issues
:url-contributors: {url-repo}/graphs/contributors
:url-rel-file-base: link:
:url-rel-tree-base: link:
ifdef::env-site,env-yard[]
:url-rel-file-base: {url-repo}/blob/HEAD/
:url-rel-tree-base: {url-repo}/tree/HEAD/
endif::[]
:url-changelog: {url-rel-file-base}CHANGELOG.adoc
:url-contribute: {url-rel-file-base}CONTRIBUTING.adoc
:url-license: {url-rel-file-base}LICENSE
:url-tests: {url-rel-tree-base}test
:url-discuss: https://discuss.asciidoctor.org
:url-chat: https://asciidoctor.zulipchat.com
:url-rubygem: https://rubygems.org/gems/asciidoctor
:url-what-is-asciidoc: {url-docs}/asciidoctor/latest/#relationship-to-asciidoc
:url-install-docker: https://github.com/asciidoctor/docker-asciidoctor
:url-opal: https://opalrb.com
:url-tilt: https://github.com/rtomayko/tilt
:url-ruby: https://www.ruby-lang.org
// images:
:image-url-screenshot: https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor/screenshot.png

{url-project}/[Asciidoctor] 是一个 _快速_ 文本处理器和发布工具链，它可以将 {url-what-is-asciidoc}[AsciiDoc] 文档转化成 HTML 5、手册页、PDF、EPUB 3 和其他格式。

Asciidoctor 还拥有一个由扩展、转换器、构建插件和工具组成的生态系统，可帮助你使用 {url-what-is-asciidoc}[AsciiDoc] 编写和发布文档。

你可以在 {url-docs} 找到这些项目的文档。

使用 {url-asciidoctorj}[AsciidoctorJ] 直接调用 Asciidoctor 的 API 运行在 Java 或者其他 Java 虚拟机中。
使用 {url-asciidoctorjs}[Asciidoctor.js] 运行在 JavaScript 当中。

ifndef::env-site,env-yard[]
该文档有如下语言的翻译版：

* {url-rel-file-base}README.adoc[English]
* {url-rel-file-base}README-fr.adoc[Français]
* {url-rel-file-base}README-jp.adoc[日本語]
* {url-rel-file-base}README-de.adoc[Deutsch]
endif::[]

.关键文档
[.compact]
* {url-docs}/asciidoctor/latest/[Asciidoctor 文档]
* {url-docs}/asciidoc/latest/[AsciiDoc 语言文档]
* {url-docs}/asciidoc/latest/syntax-quick-reference/[AsciiDoc 语法快速参考]

ifdef::status[]
image:https://img.shields.io/gem/v/asciidoctor.svg[Latest Release, link={url-rubygem}]
image:https://img.shields.io/badge/rubydoc.info-{release-version}-blue.svg[library (API) docs,link=https://www.rubydoc.info/gems/asciidoctor/{release-version}]
image:https://github.com/asciidoctor/asciidoctor/workflows/CI/badge.svg[Build Status (GitHub Actions),link={url-repo}/actions]
image:https://img.shields.io/badge/zulip-join_chat-brightgreen.svg[Project Chat (Zulip),link={url-chat}]
endif::[]

== 赞助商

我们想感谢我们的 {url-project}/supporters[赞助商] 致力于通过支持此项目来改善技术文档的生态。谢谢赞助商！没有你们的慷慨支持，Asciidoctor 不可能持续下去。

你可以通过 https://opencollective.com/asciidoctor[OpenCollective] 成为发起人来支持此项目。

== AsciiDoc 处理器和内置转换器

AsciiDoc 是语言。
Asciidoctor 是处理器。

Asciidoctor 读取 AsciiDoc 源文档，如下图左侧面板所示，并将其转换为可发布格式，如 HTML 5，如右侧面板所示。

image::{image-url-screenshot}[Preview of AsciiDoc source and corresponding rendered HTML]

Asciidoctor 提供内置的 {url-docs}/asciidoctor/latest/converters/[转换器]，默认三种格式: {url-docs}/asciidoctor/latest/html-backend/[HTML 5]， {url-docs}/asciidoctor/latest/docbook-backend/[DocBook 5] 和 {url-docs}/asciidoctor/latest/manpage-backend/[手册页]。
额外的转换器，如 PDF 和 EPUB 3 是由单独的 gem 提供的。
Asciidoctor还提供开箱即用的HTML体验，并提供 {url-docs}/asciidoctor/latest/html-backend/default-stylesheet/[默认样式] 和内置集成，如 Font Awesome (为图标设计的)、highlight.js、Rouge、和 Pygments （代码高亮），and MathJax（STEM 处理）。

== Asciidoctor 生态系统

虽然 Asciidoctor 是 Ruby 编写的，但并不是说你一定要使用 Ruby。
使用 {url-asciidoctorj}[AsciidoctorJ] 直接调用 Asciidoctor 的 API 运行在 Java 或者其他 Java 虚拟机中。
使用 {url-asciidoctorjs}[Asciidoctor.js] 运行在 JavaScript 当中。

安装 Asciidoctor 处理器只是文档体验的开始。
Asciidoctor 使你可以访问扩展和工具的生态系统，从附加的转换器到扩展语法、构建插件，再到集成的写入和预览环境：

* {url-docs}/diagram-extension/latest/[Asciidoctor 图表]
* {url-docs}/maven-tools/latest/[Maven 插件 and site 模块]
* {url-gradle-plugin}[Gradle 插件]
* {url-docs}/asciidoclet/latest/[Asciidoclet]
* {url-docs}/reveal.js-converter/latest/[reveal.js 转换器]
* {url-docs}/epub3-converter/latest/[EPUB 3 转换器]
* https://intellij-asciidoc-plugin.ahus1.de/docs[IntelliJ 插件]
* {url-docs}/asciidoctor/latest/tooling/#web-browser-add-ons-preview-only[web 浏览器扩展]
* {url-org}[更多...]

Asciidoctor 是 AsciiDoc.py 的继承者。
如果你正在使用 AsciiDoc.py，参见 {url-docs}/asciidoctor/latest/migrate/asciidoc-py/[从 AsciiDoc.py 迁移] 去学习如何升级到 Asciidoctor。

== 环境要求

Asciidoctor 可以在 Linux、macOS 和 Windows 上运行，需要 {url-ruby}[Ruby] 的以下实现之一：

* CRuby（也被称为 MRI）2.3 - 3.0
* JRuby 9.1 - 9.2
* TruffleRuby（GraalVM）

[注意]
====
如果你正在使用一个非英语的 Windows 环境，当调用 Asciidoctor 时，你可能会遇到 `Encoding::UndefinedConversionError`。
为了解决这个问题，我们建议将控制台中的编码更改为 UTF-8：

 chcp 65001

一旦你做出了这个改变，你所有的关于 Unicode 的麻烦都将挥之而去。
如果您使用的是 Eclipse 这样的IDE，请确保将编码设置为 UTF-8。当您在任何地方都使用 UTF-8 时，Asciidoctor 的工作效果最好。
====

== 安装

Asciidoctor 在 RubyGems.org 上以 RubyGem（也被称为 gem）的形式打包和分发，被命名为 {url-rubygem}[asciidoctor^]。
asciidoctor gem 可以使用 Ruby 打包工具安装在所有主要操作系统上（gem 或 bundle）。
Asciidoctor 还作为 Docker 镜像分发，作为许多 Linux 发行版的软件包分发，以及作为 macOS 的软件包分发（通过 Homebrew 和 MacPorts）。

=== Linux 包管理器

包管理器安装的 Asciidoctor 版本可能与 Asciidoctor 的最新版本不匹配。
请查阅发行版的软件包存储库，以了解每个发行版打包的版本。

* https://pkgs.alpinelinux.org/packages?name=asciidoctor[Alpine Linux (asciidoctor)]
* https://www.archlinux.org/packages/?name=asciidoctor[Arch Linux (asciidoctor)]
* https://packages.debian.org/sid/asciidoctor[Debian (asciidoctor)]
* https://apps.fedoraproject.org/packages/rubygem-asciidoctor[Fedora (asciidoctor)]
* https://software.opensuse.org/package/rubygem-asciidoctor[OpenSUSE (rubygem-asciidoctor)]
* https://packages.ubuntu.com/search?keywords=asciidoctor[Ubuntu (asciidoctor)]

如果您想使用更高版本的 Asciidoctor，参见 <<gem-install,gem 安装说明>>。

==== apk (Alpine Linux)

在 Alpine Linux 上安装 gem，打开终端并键入：

 $ sudo apk add asciidoctor

==== pacman (Arch Linux)

在基于 Arch 的发行版上安装, 打开终端并键入：

 $ sudo pacman -S asciidoctor

==== APT

在 Ubuntu 等基于 Debian 和 Debian 的发行版上，使用 APT 安装 Asciidoctor。
要安装，打开终端并键入：

 $ sudo apt-get install -y asciidoctor

==== DNF

在基于 RPM 的 Linux 发行版（如 Fedora、CentOS 和 RHEL）上，使用 DNF 包管理器安装 Asciidoctor。
要安装，打开终端并键入：

 $ sudo dnf install -y asciidoctor

=== macOS

==== Homebrew

你可以使用 https://brew.sh[Homebrew]，macOS 包管理器，去安装 Asciidoctor。
如果你的电脑上没有 Homebrew，先 https://brew.sh[安装] 它。

Homebrew 安装好以后，你就可以安装 `asciidoctor` gem 了。
打开终端并键入：

 $ brew install asciidoctor

Homebrew 安装 `asciidoctor` gem 到一个独有的“前缀”中，它独立于系统的 gem。

==== MacPorts

你也可以使用 https://www.macports.org[MacPorts]，macOS 的包管理器，用于安装 Asciidoctor。
如果您的计算机上没有 MacPorts，先 https://www.macports.org/install.php[安装] 。

安装 MacPorts 后，你就可以通过 https://ports.macports.org/port/asciidoctor/[Asciidoctor port] 安装 `asciidoctor` gem 了。
打开终端并键入：

 $ sudo port install asciidoctor

=== Windows

要在 Windows 上使用 Asciidoctor，你有两个选择：

==== Chocolatey

当你已经使用 https://chocolatey.org[chocolatey] ，你可以使用：

 choco install ruby

然后参照 <<gem-install,gem 安装说明>>。

==== Rubyinstaller

或者你可以使用 https://rubyinstaller.org/downloads/[Rubyinstaller]，下载它，然后参照 <<gem-install,gem 安装说明>>。

[#gem-install]
=== gem install

在你使用 `gem install` 安装 AsciiDoctor 之前，你应该安装 https://rvm.io[RVM]（或者类似的软件）以在 home 目录下安装 Ruby.
然后，你可以安全地使用 `gem` 命令去安装或更新 Asciidoctor gem，或者其它的 `gem` 命令。
当使用 RVM,gem 安装在与系统隔离的位置。
（您不应该使用 gem 命令安装系统范围的 gem）

使用 RVM 安装 Ruby 并使用 `rvm use 3.0` 激活 Ruby 后，打开终端并键入：

 $ gem install asciidoctor

如果要安装预发布版本（例如，候选发布版本），请使用：

 $ gem install asciidoctor --pre

=== Docker

参见 {url-install-docker}[使用 Docker 安装 Asciidoctor]。

=== Bundler

. 在项目的根目录（或当前目录）中创建一个 Gemfile
. 将 `asciidoctor` gem 像下面这样加入到 Gemfile 中：
+
[subs=attributes+]
----
source 'https://rubygems.org'
gem 'asciidoctor'
# or specify the version explicitly
# gem 'asciidoctor', '{release-version}'
----

. 保存 Gemfile
. 打开命令行安装 the gem，如下：

 $ bundle

要更新 gem，在 Gemfile 指定新版本，再次运行 `bundle`。
使用 `bundle update`（没有指定 gem）是不推荐的，因为它也更新了其他的 gem，可能这并不是预期的结果。

== 更新

如果你使用包管理器来安装 Asciidoctor，你的操作系统可能配置为自动更新，在这种情况下，您不需要手动更新 gem。

=== apk (Alpine Linux)

更新 gem，使用：

 $ sudo apk add -u asciidoctor

=== APT

更新 gem，使用：

 $ sudo apt-get upgrade -y asciidoctor

=== DNF

更新 gem，使用：

 $ sudo dnf update -y asciidoctor

=== Homebrew (macOS)

更新 gem，使用：

 $ brew update
 $ brew upgrade asciidoctor

=== MacPorts (macOS)

更新 gem，使用：

 $ sudo port selfupdate
 $ sudo port upgrade asciidoctor

=== gem install

如果您以前使用 `gem` 命令安装 Asciidoctor，那么当新版本发布时，您需要手动升级 Asciidoctor。
你可以执行下面的命令来进行更新：

 $ gem install asciidoctor

当你使用 `gem install` 安装 gem 的新版本时，你最终会安装多个版本。
使用下面的命令来移除旧版本：

 $ gem cleanup asciidoctor

== 使用

If the Asciidoctor gem installed successfully, the `asciidoctor` command line interface (CLI) will be available on your PATH.
To verify it's available, run the following in your terminal:

 $ asciidoctor --version

You should see information about the Asciidoctor version and your Ruby environment printed in the terminal.

[.output,subs=attributes+]
....
Asciidoctor {release-version} [https://asciidoctor.org]
Runtime Environment (ruby 3.0.1p64 [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
....

=== Command line interface (CLI)

The `asciidoctor` command allows you to invoke Asciidoctor from the command line (i.e., a terminal).

The following command converts the file README.adoc to HTML and saves the result to the file README.html in the same directory.
The name of the generated HTML file is derived from the source file by changing its file extension to `.html`.

 $ asciidoctor README.adoc

You can control the Asciidoctor processor by adding various flags and switches, which you can learn about using:

 $ asciidoctor --help

For instance, to write the file to a different directory, use:

 $ asciidoctor -D output README.adoc

The `asciidoctor` {url-manpage}[man page] provides a complete reference of the command line interface.

Refer to the following resources to learn more about how to use the `asciidoctor` command.

* {url-docs}/asciidoctor/latest/cli/[Process AsciiDoc using the CLI]
* {url-docs}/asciidoctor/latest/cli/options/[CLI options]

=== Ruby API

Asciidoctor also provides an API.
The API is intended for integration with other Ruby software, such as Rails, GitHub, and GitLab, as well as other languages, such as Java (via AsciidoctorJ) and JavaScript (via Asciidoctor.js).

To use Asciidoctor in your application, you first need to require the gem:

----
require 'asciidoctor'
----

You can then convert an AsciiDoc source file to an HTML file using:

----
Asciidoctor.convert_file 'README.adoc', to_file: true, safe: :safe
----

WARNING: When using Asciidoctor via the API, the default safe mode is `:secure`.
In secure mode, several core features are disabled, including the `include` directive.
If you want to enable these features, you'll need to explicitly set the safe mode to `:server` (recommended) or `:safe`.

You can also convert an AsciiDoc string to embeddable HTML (for inserting in an HTML page) using:

----
content = '_Zen_ in the art of writing https://asciidoctor.org[AsciiDoc].'
Asciidoctor.convert content, safe: :safe
----

If you want the full HTML document, enable the `header_footer` option as follows:

----
content = '_Zen_ in the art of writing https://asciidoctor.org[AsciiDoc].'
html = Asciidoctor.convert content, header_footer: true, safe: :safe
----

If you need access to the parsed document, you can split the conversion into discrete steps:

----
content = '_Zen_ in the art of writing https://asciidoctor.org[AsciiDoc].'
document = Asciidoctor.load content, header_footer: true, safe: :safe
puts document.doctitle
html = document.convert
----

Keep in mind that if you don't like the output Asciidoctor produces, _you can change it!_
Asciidoctor supports custom converters that can handle converting from the parsed document to the generated output.

One easy way to customize the output piecemeal is by using the template converter.
The template converter allows you to supply a {url-tilt}[Tilt]-supported template file to handle converting any node in the document.

However you go about it, you _can_ have 100% control over the output.
For more information about how to use the API or to customize the output, see:

* {url-docs}/asciidoctor/latest/api/[Process AsciiDoc using the API]
* {url-docs}/asciidoctor/latest/api/options/[API options]
* {url-docs}/asciidoctor/latest/safe-modes/[Safe modes]

== Contributing

New contributors are always welcome!
If you discover errors or omissions in the source code, documentation, or website content, please don't hesitate to submit an issue or open a pull request with a fix.

Here are some ways *you* can contribute:

* by using prerelease (alpha, beta or preview) versions
* by reporting bugs
* by suggesting new features
* by writing or editing documentation
* by writing code with tests -- _No patch is too small._
** fix typos
** add comments
** clean up inconsistent whitespace
** write tests!
* by refactoring code
* by fixing {url-issues}[issues]
* by reviewing patches

The {url-contribute}[Contributing] guide provides information on how to create, style, and submit issues, feature requests, code, and documentation to Asciidoctor.

== Getting Help

Asciidoctor is developed to help you easily write and publish your content.
But we can't do it without your feedback!
We encourage you to ask questions and discuss any aspects of the project on the discussion list, on Twitter or in the chat room.

Chat (Zulip):: {url-chat}
Discussion list (Nabble):: {url-discuss}
Twitter:: Follow https://twitter.com/asciidoctor[@asciidoctor] or search for the https://twitter.com/search?f=tweets&q=%23asciidoctor[#asciidoctor] hashtag

ifdef::env-github[]
Further information and documentation about Asciidoctor can be found on the project's website.

{url-project}[Home] | {url-news}[News] | {url-docs}[Docs]
endif::[]

The Asciidoctor organization on GitHub hosts the project's source code, issue tracker, and sub-projects.

Source repository (git):: {url-repo}
Issue tracker:: {url-issues}
Asciidoctor organization on GitHub:: {url-org}

== Code of Conduct

The core Asciidoctor project is governed by the https://github.com/asciidoctor/.github/blob/HEAD/CODE-OF-CONDUCT.md[Code of Conduct] for the Asciidoctor community of projects.
By participating, you're agreeing to honor this code.
Let's work together to make this a welcoming, professional, inclusive, and safe environment for everyone.

== Versioning and Release Policy

This project adheres to semantic versioning (*major.minor.patch*).
Typically, patch releases are only made for the current minor release.
However, exceptions are made on a case-by-case basis to address security vulnerabilities and other high-priority issues.

== Copyright and License

Copyright (C) 2012-present Dan Allen, Sarah White, Ryan Waldron, and the individual contributors to Asciidoctor.
Use of this software is granted under the terms of the MIT License.

See the {url-license}[LICENSE] for the full license text.

== Authors

*Asciidoctor* is led by https://github.com/mojavelinux[Dan Allen] and https://github.com/graphitefriction[Sarah White] and has received contributions from {url-contributors}[many individuals] in Asciidoctor's awesome community.
The project was initiated in 2012 by https://github.com/erebor[Ryan Waldron] based on a prototype written by https://github.com/nickh[Nick Hengeveld] for the Git website.

*AsciiDoc.py* was started and maintained by Stuart Rackham from https://github.com/asciidoc-py/asciidoc-py2/blob/HEAD/CHANGELOG.txt[2002 to 2013] and has received contributions from many individuals in the https://github.com/asciidoc-py/asciidoc-py2/graphs/contributors[AsciiDoc.py community].

== Trademarks

AsciiDoc(R) and AsciiDoc Language(TM) are trademarks of the Eclipse Foundation, Inc.

ifndef::env-site[]
== Changelog

ifeval::[{safe-mode-level} < 20]
include::CHANGELOG.adoc[tag=compact,leveloffset=+1]
endif::[]

参见 {url-changelog}[CHANGELOG] 查看对旧版本中更改的完整列表。
endif::[]
