site:
  title: Asciidoctor Docs
  url: https://asciidoctor.org/docs
  start_page: asciidoctor::index.adoc
asciidoc:
  attributes:
    experimental: ''
    example-caption: ~
    hide-uri-scheme: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    source-language: asciidoc
    table-caption: ~
    url-project: https://asciidoctor.org
    url-manpage: https://asciidoctor.org/man/asciidoctor
    url-org: https://github.com/asciidoctor
    url-license: https://github.com/asciidoctor/asciidoctor/blob/master/LICENSE
    url-repo: https://github.com/asciidoctor/asciidoctor
    url-tests: https://github.com/asciidoctor/asciidoctor/tree/master/test
    url-exten-lab: https://github.com/asciidoctor/asciidoctor-extensions-lab
    url-rubygem: https://rubygems.org/gems/asciidoctor
    url-alpine: https://pkgs.alpinelinux.org/packages?name=asciidoctor
    url-fedora: https://apps.fedoraproject.org/packages/rubygem-asciidoctor
    url-tilt: https://github.com/rtomayko/tilt
    url-foundation: https://foundation.zurb.com
    url-jruby: https://jruby.org
    url-rewrite: https://github.com/ocpsoft/rewrite/tree/master/transform-markup
    url-uri: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
    url-html-ref: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
    url-unicode: https://en.wikipedia.org/wiki/List_of_Unicode_characters
    url-asciimath: https://docs.mathjax.org/en/latest/asciimath.html
    url-latexmath: https://docs.mathjax.org/en/latest/tex.html
    url-mathjax: https://www.mathjax.org
    url-mathjax-docs: https://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference
    url-coderay: http://coderay.rubychan.de/
    url-coderay-gem: https://rubygems.org/gems/coderay
    url-highlightjs: https://highlightjs.org/
    url-highlightjs-lang: https://highlightjs.org/download/
    url-highlightjs-cdn: https://cdnjs.com/libraries/highlight.js
    url-prettify: https://code.google.com/p/google-code-prettify
    url-pygments: http://pygments.org
    url-pygments-lang: http://pygments.org/languages/
    url-pygments-gem: https://rubygems.org/gems/pygments.rb
    url-python: https://www.python.org
    url-rouge: http://rouge.jneen.net
content:
  sources:
  - url: /home/apex/projects/asciidoctor
    branches: HEAD
#  - url: git@github.com:asciidoctor/asciidoctor.git
#    branches:
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
#  supplemental_files: ./supplemental-ui
output:
  dir: ./public
