= Footnotes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
anchor from user manual: user-footnotes
Included in:
- user-manual: Footnote
////

A footnote is created with the footnote macro (`+footnote:[]+`).
If you plan to reference a footnote more than once, use the footnoteref macro (`+footnoteref:[]+`).

.Footnote syntax
[source]
----
include::{partialsdir}/ex-footnote.adoc[tag=base-c]
----
<1> Insert the footnote macro directly after any punctuation. Note that the footnote macro only uses one colon (`:`).
<2> Insert the footnote's content within the square brackets (`+[]+`). The text may span several lines.
<3> If you plan to reuse a footnote, use `footnoteref:` and provide a unique ID in the first position inside the square brackets when you create it.
<4> Separate the ID from the footnote text with a comma. Do not enter a space between the comma and the footnote text.
<5> The next time you reference the footnote you only need to insert the ID in the square brackets.

The footnotes will be numbered consecutively throughout the article.

.Rendered footnotes
====
[.unstyled]
|===
a|
include::{partialsdir}/ex-footnote.adoc[tag=base-x]
|===
====

////
Roll this text out in 1.5.7

A footnote is created with the footnote macro (`+footnote:[]+`).

.Footnote macro syntax
[source]
----
include::ex-footnote.adoc[tag=base-c]
----
<1> Insert the footnote macro directly after any punctuation. The footnote macro only uses one colon.
<2> The first time you enter a footnote you want to reuse, give it a unique ID directly after the `:`.
<3> Insert the footnote's content within the square brackets of the macro. The text may span several lines.
<4> The next time you reference the footnote you only need to insert the ID, followed by an empty set of square brackets.

The footnotes will be numbered consecutively throughout the document.

.Rendered footnotes
====
[.unstyled]
|===
a|
include::ex-footnote.adoc[tag=base-x]
|===
====
////
