= Migrate from DocBook XML to Asciidoctor
:navtitle: Migrate from DocBook XML
:url-docbookrx: https://github.com/asciidoctor/docbookrx
// docbookrx.adoc, included in user-manual: Convert DocBook XML to AsciiDoc

One of the things Asciidoctor excels at is converting AsciiDoc source into valid and well-formed DocBook XML content.

What if you're in the position where you need to go the other way: migrate all your legacy DocBook XML content to AsciiDoc?
The prescription (℞) you need to get rid of your DocBook pains could be {url-docbookrx}[DocBookRx^].

DocBookRx is an early version of a DocBook to AsciiDoc converter written in Ruby.
This converter is far from perfect at the moment, but it improves with each document it converts.

The plan is to evolve it into a robust library for performing this conversion in a reliable way.
You can read more about this initiative in the {url-docbookrx}#readme[README^].

The best thing about this tool is all the active users who are putting it through its paces.
The more advanced the DocBook XML this tool tackles, and the more feedback we receive, the better the tool will become.
Use it today to escape from XML hell!

== Doxygen - Just What the DocBookRx Ordered

It is also important to mention that Doxygen supports DocBook, and therefore a pathway from Doxygen to AsciiDoc is possible.
Simply set, `GENERATE_DOCBOOK` to `YES` in the Doxygen configuration file and run the doxygen command to generate the DocBook XML output.
Once the DocBook XMl files are generated, run DocBookRx on the files to generate AsciiDoc files.
Some post processing might be necessary.
