= Core Concepts

Asciidoctor parses AsciiDoc documents and then uses a converter to generate the output format of your choice, such as HTML, DocBook, or PDF.
During this process, Asciidoctor applies its default stylesheet or the stylesheet you provide.

== What's a converter?

A converter takes AsciiDoc and transforms it into another format.
Each converter produces a specific output format, such as HTML or DocBook XML.

Asciidoctor comes with built-in HTML, DocBook, and manual page (man page) converters.
You can also plug in EPUB, PDF, LaTeX, HTML slide deck, and static website converters.
See xref:converters.adoc[Choose a Converter] for descriptions of all of the supported converters.

== What's the default stylesheet?

Asciidoctor comes with a stylesheet that's applied to the output of the built-in converters.
This stylesheet is applied by default unless you tell Asciidoctor to use another stylesheet.
See xref:html:apply-stylesheet.adoc[Apply a Stylesheet] to learn about the default and custom stylesheet options.

== Next

* xref:converters.adoc[Choose a converter] that produces the output format you want.
* Learn how to use the xref:cli.adoc[Asciidoctor command line interface].
