= Process AsciiDoc Using the API
:url-api: https://www.rubydoc.info/gems/asciidoctor
////
API introduction for Asciidoctor
included in the user-manual Quickstarts, Using the Ruby API
doc-asciidoctorj is now url-asciidoctorj-docs but! that means I need to fix docref: link:/docs and doc-asciidoctorj: {docref}/asciidoctorj
////

In addition to its CLI, Asciidoctor provides a Ruby API.
The API is intended for integration with other software projects and is suitable for server-side applications, such as Rails, Sinatra and GitHub.

Asciidoctor also has a Java API that mirrors the Ruby API.
The Java API calls through to the Ruby API using an embedded JRuby runtime.
See the AsciidoctorJ documentation for more information.

== Load and convert a document using the API

To use Asciidoctor in your application, you first need to require the gem:

[source,ruby]
require 'asciidoctor'

This one statement makes all of the {url-api}[public APIs in Asciidoctor] available to your script or application.
Now you can start processing AsciiDoc documents.
The main entry points in the Asciidoctor API are the static methods to load or convert AsciiDoc documents, which we'll cover on this page.

To parse a file into an `Asciidoctor::Document` object:

[source,ruby]
doc = Asciidoctor.load_file 'my-sample.adoc'

You can get information about the document:

[source,ruby]
puts doc.doctitle
puts doc.attributes

To convert a file containing AsciiDoc markup to HTML 5, use:

[source,ruby]
Asciidoctor.convert_file 'my-sample.adoc'

The command will output to the file [.path]_my-sample.html_ in the same directory.

You can convert the file to DocBook 5.0 by setting the `:backend` option to `'docbook'`:

[source,ruby]
Asciidoctor.convert_file 'my-sample.adoc', backend: 'docbook'

The command will output to the file [.path]_my-sample.xml_ in the same directory.
