= Extensions
:url-exten-lab: https://github.com/asciidoctor/asciidoctor-extensions-lab

Extensions are central to the power of AsciiDoc because they open up the language to new use cases.
Asciidoctor provides an extension API that offers a set of extension points.
Extensions in Asciidoctor are easy to write, powerful, and simple to distribute.

Asciidoctor also allows extensions to be written using the full power of the programming language of your asciidoctor variant: Ruby, Java or other JVM based languages, or Javascript.
An extension may be included in custom code or packaged and distributed using a language-standard mechanism such as Gems, Jars/Maven, or npm packages.

There are two general types of processors:

Document Processor::
  A document processor does not have an explicit invocation in the document.
Except for `IncludeProcessor`, a document processor is invoked at the appropriate stage of processing with the entire document.
Syntax Processor::
  A syntax processor has a name and is invoked when that name is encountered in the document.

== Available extension points

Asciidoctor provides the following extension points, shown in the order of invocation:
To be more specific, these are types of Processor, and a concrete implementation extends the corresponding Processor subclasses.

Preprocessor (Document)::
Processes the raw source lines before they are passed to the parser.
See xref:processors/preprocessor.adoc[].

Include processor (Document)::
Processes the `include::<filename>[]` directive.
See xref:processors/include-processor.adoc[].

Block processor (Syntax)::
Processes a block of content marked with a custom block style (i.e., `[custom]`). (similar to an AsciiDoc filter)
See xref:processors/block-processor.adoc[].

Compound block processor:::
Register a custom block named `collapsible` that transforms a listing block into a compound block.
See xref:processors/compound-block-processor.adoc[].

Block macro processor (Syntax)::
Registers a custom block macro and processes it (e.g., `gist::12345[]`).
See xref:processors/block-macro-processor.adoc[].

Tree processor (Document)::
Processes the [.class]#Asciidoctor::Document# (AST) once parsing is complete.
See xref:processors/tree-processor.adoc[].

Inline macro processor (Syntax)::
Registers a custom inline macro and processes it (e.g., `btn:[Save]`).
See xref:processors/inline-macro-processor.adoc[].

Docinfo Processor (Document)::
Adds additional content to the header or footer regions of the generated document.
See xref:processors/docinfo-processor.adoc[].

Postprocessor (Document)::
Processes the output after the document has been converted, but before it's written to disk.
See xref:processors/postprocessor.adoc[].

There are additional extension examples in the {url-exten-lab}[Asciidoctor extensions lab^].

== Aspects of extension development

There are four main aspects to extension development:

Registration::
This involves telling Asciidoctor that you are using the extension in some context.

Capabilities::
This involves telling Asciidoctor about the extension, often with information such as `name` and which contexts it can appear in.

Code::
This is the actual code that implements the extension functionality.

Packaging::
This involves making the code available to Asciidoctor for the preceding three aspects.