= Extensions
:url-exten-lab: https://github.com/asciidoctor/asciidoctor-extensions-lab

Extensions are central to the power of AsciiDoc because they open up the language to new use cases.
Asciidoctor provides an extension API that offers a set of extension points.
Extensions in Asciidoctor are easy to write, powerful, and simple to distribute.

Asciidoctor also allows extensions to be written using the full power of the programming language of your Asciidoctor variant: Ruby, Java or other JVM based languages, or Javascript.
An extension may be included in custom code or packaged and distributed using a language-standard mechanism such as Gems, Jars/Maven, or npm packages.

There are two general types of processors:

Document Processor::
  A document processor does not have an explicit invocation in the document.
Except for `IncludeProcessor`, a document processor is invoked at the appropriate stage of processing with the entire document.
Syntax Processor::
  A syntax processor has a name and is invoked when that name is encountered in the document.

== Available extension points

Asciidoctor provides the following extension points, shown in the order of invocation.
(Block processors and Block Macro processors are called during the parse stage as uses are encountered in the document.)
To be more specific, these are types of Processor, and a concrete implementation extends the corresponding Processor subclass.

xref:processors/include-processor.adoc[] (Document)::
Processes the `include::<filename>[]` directive.

xref:processors/preprocessor.adoc[] (Document)::
Processes the raw source lines before they are passed to the parser.

xref:processors/block-processor.adoc[] (Syntax)::
Processes a block of content marked with a custom block style (i.e., `[custom]`). (similar to an AsciiDoc filter)

xref:processors/block-macro-processor.adoc[] (Syntax)::
Registers a custom block macro and processes it (e.g., `gist::12345[]`).

xref:processors/tree-processor.adoc[] (Document)::
Processes the [.class]#Asciidoctor::Document# (AST) once parsing is complete.

xref:processors/inline-macro-processor.adoc[] (Syntax)::
Registers a custom inline macro and processes it (e.g., `pass:[btn:[Save]]`).

xref:processors/docinfo-processor.adoc[] (Document)::
Adds additional content to the header or footer regions of the generated document.

xref:processors/postprocessor.adoc[] (Document)::
Processes the output after the document has been converted, but before it's written to disk.

There are additional extension examples in the {url-exten-lab}[Asciidoctor extensions lab^].

== Aspects of extension development

There are four main aspects to extension development:

Code::
This is the actual code that implements the extension functionality.
The inputs and expected outputs are described on the processor-specific pages linked above.

Capabilities::
This involves telling Asciidoctor about the extension, often with information such as `name` and which contexts it can appear in.
General information is presented xref:processor.adoc[here] with more specific details on the processor-specific pages.

Registration::
This involves xref:register.adoc[telling Asciidoctor] that you are using the extension in some context.
Usually this is done in code that forms a xref:register.adoc#groups[group].

Packaging::
xref:packaging.adoc[This] involves making the code available to Asciidoctor for the preceding three aspects.