= Callouts
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
From callouts-intro.adoc, in user manual (peamble to Copy and paste friendly callouts)
////

Callout numbers (aka callouts) provide a means to add annotations to lines in a verbatim block.

== Callout syntax

Each callout number used in a verbatim block must appear twice.
The first use, which goes within the verbatim block, marks the line being annotated (i.e., the target).
The second use, which goes below the verbatim block, defines the annotation text.
Multiple callout numbers may be used on a single line.

IMPORTANT: The callout number (at the target) must be placed at the end of the line.

Here's a basic example of a verbatim block that uses callouts:

[source,subs=-callouts]
....
include::{partialsdir}/ex-callout.adoc[tag=basic]
....

Here's how this example gets rendered:

====
include::{partialsdir}/ex-callout.adoc[tag=basic]
====

Since callout number can interfere with the syntax of the code they are annotating, Asciidoctor provides several features to hide the callout numbers from both the source and the converted document.
The sections that follow detail these features.

== Copy and paste friendly callouts
////
From callout-copy.adoc, included in:
- user-manual: callouts: Callouts don't get caught in copy
////

In versions prior to Asciidoctor 0.1.4, when a reader visiting an HTML page generated by Asciidoctor selected source code from a listing that contained callouts and copied it, the callout numbers would get caught up in the copied text.
If the reader pasted that code and tried to run it, likely the extra characters from the callouts would cause compile or runtime errors.

Asciidoctor uses CSS to prevent callouts from being selected.

On the other side of the coin, you don't want the callout annotations or CSS messing up your raw source code either.
You can tuck your callouts neatly behind line comments.
Asciidoctor will recognize the line comments characters in front of a callout number, optionally offset by a space, and remove them when converting the document.

Here are the line comments that are supported:

[source,subs=specialcharacters]
....
include::{partialsdir}/ex-callout.adoc[tag=b-nonselect]
....

Here's how it looks when rendered:

====
include::{partialsdir}/ex-callout.adoc[tag=b-nonselect]
====

=== XML callouts
////
From callout-xml.adoc, included in:
- user-manual: callouts: XML-friendly callouts
////

XML doesn't have line comments, so our "`tuck the callout behind a line comment`" trick doesn't work here.
To use callouts in XML, you must place the callout's angled brackets around the the XML comment and callout number.

Here's how it appears in a listing:

[source,subs=specialcharacters]
....
include::{partialsdir}/ex-callout.adoc[tag=source-xml]
....

Here's how it looks when rendered:

====
include::{partialsdir}/ex-callout.adoc[tag=source-xml]
====

Notice the comment has been replaced with a circled number that cannot be selected (if not using font icons it will be
rendered differently and selectable).
Now both you and the reader can copy and paste XML source code containing callouts without worrying about errors.

== Callout icons
////
From callout-icon.adoc, included in:
- user-manual: callouts: Callout icons
////

The font icons setting also enables callout icons drawn using CSS.

[source]
----
include::{partialsdir}/ex-callout.adoc[tag=co-icon]
----
<1> Activates the font-based icons in the HTML5 backend.
<2> Admonition block that uses a font-based icon.
