////
Included in:

- user-manual: Paragraphs
- user-manual: Text formatting
- quick-syntax
- writers-guide: quoted text
////

// tag::para[]
This journey begins one late Monday afternoon in Antwerp.
Our team desperately needs coffee, but none of us dare open the office door.

To leave means code dismemberment and certain death.
// end::para[]

// tag::b-para[]
Paragraphs don't require any special markup in AsciiDoc.
A paragraph is just one or more lines of consecutive text.

To begin a new paragraph, separate it by at least one blank line.
Newlines within a paragraph are not displayed.
// end::b-para[]

// tag::hb-all[]
Rubies are red, +
Topazes are blue.

[%hardbreaks]
Ruby is red.
Java is black.
// end::hb-all[]

// tag::hb[]
Rubies are red, +
Topazes are blue.
// end::hb[]

// tag::hb-p[]
[%hardbreaks]
Ruby is red.
Java is black.
// end::hb-p[]

// tag::b-hb[]
To preserve a line break, end the line in a space followed by a plus sign. +
This results in a visible line break (e.g., `<br>`) between the lines.
// end::b-hb[]

// tag::hb-attr[]
= Line Break Doc Title
:hardbreaks:

Rubies are red,
Topazes are blue.
// end::hb-attr[]

// tag::lead[]
[.lead]
This is the ultimate paragraph.
// end::lead[]

// tag::b-lead[]
[.lead]
This text will be styled as a lead paragraph (i.e., larger font).
// end::b-lead[]

// tag::b-i[]
_To tame_ the wild wolpertingers we needed to build a *charm*.
But **u**ltimate victory could only be won if we divined the *_true name_* of the __war__lock.
// end::b-i[]

// tag::b-i-n[]
_To tame_ the wild wolpertingers we needed to build a *charm*.
But **u**ltimate victory could only be won if we divined the *_true name_* of the __war__lock.
// end::b-i-n[]

// tag::b-bold-italic-mono[]
*bold phrase* & **char**acter**s**

_italic phrase_ & __char__acter__s__

*_bold italic phrase_* & **__char__**acter**__s__**

`monospace phrase` & ``char``acter``s``

`*monospace bold phrase*` & ``**char**``acter``**s**``

`_monospace italic phrase_` & ``__char__``acter``__s__``

`*_monospace bold italic phrase_*` &
``**__char__**``acter``**__s__**``
// end::b-bold-italic-mono[]

// tag::c-quote-co[]
"`What kind of charm?`" Lazarus asked. "`An odoriferous one or a mineral one?`" // <1>

Kizmet shrugged. "`The note from Olaf's desk says '`wormwood and licorice,`' but these could be normal groceries for werewolves.`" // <2>
// end::c-quote-co[]

// tag::c-quote[]
"`What kind of charm?`" Lazarus asked. "`An odoriferous one or a mineral one?`"

Kizmet shrugged. "`The note from Olaf's desk says '`wormwood and licorice,`' but these could be normal groceries for werewolves.`"
// end::c-quote[]

// tag::b-c-quote[]
"`double curved quotes`"

'`single curved quotes`'

Olaf's desk was a mess.

All of the werewolves`' desks were a mess.

Olaf had been with the company since the `'60s.
// end::b-c-quote[]

// tag::apos[]
Olaf had been with the company since the `'60s.
His desk overflowed with heaps of paper, apple cores and squeaky toys.
We couldn't find Olaf's keyboard.
The state of his desk was replicated, in triplicate, across all of the werewolves`' desks.
// end::apos[]

// tag::sub-sup[]
"`Well the H~2~O formula written on their whiteboard could be part of a shopping list, but I don't think the local bodega sells E=mc^2^,`" Lazarus replied.
// end::sub-sup[]

// tag::b-sub-sup[]
^super^script phrase

~sub~script phrase
// end::b-sub-sup[]

// tag::mono[]
"`Wait!`" Indigo plucked a small vial from her desk's top drawer and held it toward us.
The vial's label read: E=mc^2^; `the scent of science`; `_smell like a genius_`.
// end::mono[]

// tag::b-mono-code[]
Reference code like `types` or `methods` inline.
// end::b-mono-code[]

// tag::highlight[]
Werewolves are #allergic to cinnamon#.
// end::highlight[]

// tag::highlight-html[]
<mark>mark element</mark>
// end::highlight-html[]

// tag::css-co[]
Do werewolves believe in [small]#small print#? // <1>

[big]##O##nce upon an infinite loop.
// end::css-co[]

// tag::css[]
Do werewolves believe in [small]#small print#?

[big]##O##nce upon an infinite loop.
// end::css[]

// tag::css-all[]
Werewolves are allergic to #cassia cinnamon#.

Did the werewolves read the [.small]#small print#?

Where did all the [.underline]#cores# run off to?

We need [.line-through]#ten# make that twenty VMs.

[.big]##O##nce upon an infinite loop.
// end::css-all[]

// tag::css-custom[]
Type the word [.userinput]#asciidoctor# into the search bar.
// end::css-custom[]

// tag::css-custom-html[]
<span class="userinput">asciidoctor</span>
// end::css-custom-html[]

////
phrase styled by CSS class .small#
////
