= Document Types
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Article (keyword: `article`)::
The default doctype.
In DocBook, includes the appendix, abstract, bibliography, glossary, and index sections.

Book (keyword: `book`)::
Builds on the article doctype with the additional ability to use a top-level title as part titles, includes the appendix, dedication, preface, bibliography, glossary, index, and colophon.
There's also the concept of a multi-part book, but the distinction from a regular book is determined by the content.
A book only has chapters and special sections, whereas a multi-part book is divided by parts that each contain one or more chapters or special sections.

Man page (keyword: `manpage`)::
Used for producing a roff or HTML-formatted manual page (man page) for Unix and Unix-like operating systems.
This doctype instructs the parser to recognize a special document header and section naming conventions for organizing the AsciiDoc content as a man page.
See xref:manpage:index.adoc[Man Pages] for details on how structure a man page using AsciiDoc and generate it with Asciidoctor.

Inline (keyword: `inline`)::
Asciidoctor only.
There may be cases when you only want to apply inline AsciiDoc formatting to input text without wrapping it in a block element.
For example, in the Asciidoclet project (AsciiDoc in Javadoc), only the inline formatting is needed for the text in Javadoc tags.
// {asciidoclet-ref}[Asciidoclet project]

== Inline doctype

The rules for the inline doctype are as follows:

* Only a single paragraph is read from the AsciiDoc source.
* Inline formatting is applied.
* The output is not wrapped in the normal paragraph tags.

Given the following input:

[source]
https://asciidoctor.org[AsciiDoc] is a _lightweight_ markup language...

Processing it with the options `doctype=inline` and `backend=html5` produces:

[source,html]
<a href="https://asciidoctor.org">AsciiDoc</a> is a <em>lightweight</em> markup language&#8230;

The inline doctype allows the Asciidoctor processor to cover the full range of applications, from unstructured (inline) text to full, standalone documents!
