= Text Editors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// text-editor.adoc, included in the install-toolchain document and user manual

Since AsciiDoc syntax is just plain text, you can write an AsciiDoc document using _any_ text editor.
You don't need complex word processing programs like Microsoft Word, OpenOffice Writer or Google Docs.
In fact, you shouldn't use these programs because they add cruft to your document that you can't see that makes conversion tedious.

While it's true any text editor will do, an editor that supports syntax highlighting for AsciiDoc may be more helpful.
The color brings contrast to the text, making it easier to read.
The highlighting also confirms when you've entered the correct syntax for an inline or block element.

The most popular application for editing plain text on macOS is *TextMate*.
A similar choice on Linux is *GEdit*.
On Windows, stay away from Notepad and Wordpad because they produce plain text which is not cross-platform friendly.
Opt instead for a competent text editor like *Notepad++*.
If you're a programmer (or a writer with an inner geek), you'll likely prefer *Vim*, *Emacs*, or *Sublime Text*, all of which are available cross-platform.
For those that work on multiple platforms, *Atom* is a consistent choice with many add-on packages for working with AsciiDoc files.
The key feature all these editors share is syntax highlighting for AsciiDoc.

TIP: Previewing the output of the document while editing can be helpful.
To learn how to setup instant preview, check out the xref:edit-with-live-preview.adoc[Editing AsciiDoc with Live Preview tutorial].
