= Install Asciidoctor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
from install-upgrade-asciidoctor.adoc
included in the install-toolchain and user-manual
////

//tag::intro[]
Asciidoctor can be installed using the `gem` command, Bundler or a Linux package manager.
//end::intro[]

== Install using `gem`

//tag::gem[]
To install Asciidoctor using the `gem` command:

. Open a terminal
. Type the following `gem` command

 $ gem install asciidoctor

If the Asciidoctor gem installed successfully, the `asciidoctor` command line interface (CLI) will be available on your PATH.
To confirm that Asciidoctor is available, execute:

 $ asciidoctor --version

The following output should appear in your terminal:

 Asciidoctor 1.5.7 [https://asciidoctor.org]
 Runtime Environment (ruby 2.3.0p0 [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

//end::gem[]

== Install using Bundler

//tag::bundler[]
To install Asciidoctor for a project using Bundler:

. Open your project's Gemfile
. Add the `asciidoctor` gem using:

 gem 'asciidoctor'

. Save the Gemfile
. Open a terminal
. Install the gem using the `bundle` command:

 $ bundle

//end::bundler[]

== Install on Fedora

//tag::yum[]
To install Asciidoctor on Fedora (or RHEL via EPEL) using the {url-fedora}[rubygem-asciidoctor] package:

. Open a terminal
. Run the installation command on Fedora:
+
 $ sudo dnf install asciidoctor

The benefit of installing the gem using this method is that the package manager will also install Ruby and RubyGems if not already on your machine.
//end::yum[]

== Install on Debian or Ubuntu

//tag::aptget[]
To install Asciidoctor on Debian or Ubuntu:

. Open a terminal
. Type the following `apt-get` command using sudo:

 $ sudo apt-get install asciidoctor

The benefit of installing the gem via `apt-get` is that the package manager will also install Ruby and RubyGems if not already on your machine.
//end::aptget[]

== Install on Alpine Linux

//tag::apk[]
To install Asciidoctor on Alpine Linux using the {url-alpine}[asciidoctor package]:

. Open a terminal
. Type the following `apk` command using sudo:

 $ sudo apk add asciidoctor

The benefit of installing the gem via `apk` is that the package manager will also install Ruby and RubyGems if not already on your machine.
//end::apk[]
