= Install Asciidoctor

To simplify installation, Asciidoctor is packaged and distributed as a RubyGem (aka gem) to {url-rubygem}/asciidoctor[RubyGems.org^].
It's also distributed as a package for popular Linux distributions and macOS.
In addition to running on Ruby, Asciidoctor can be executed on a JVM using {url-asciidoctorj}[AsciidoctorJ^] or in any JavaScript environment (including the browser) using xref:asciidoctor.js::index.adoc[Asciidoctor.js].

== Installation methods

Asciidoctor can be installed using:

* package managers for popular Linux distributions,
* Homebrew for macOS,
* the `gem install` command (recommended for Windows users or if you'll be installing additional gems),
* the Asciidoctor Docker image, or
* Bundler.

The benefit of using your operating system's package manager to install the gem is that it handles installing Ruby and the RubyGems library if those packages are not already installed on your machine.

=== Linux package managers

The version of Asciidoctor installed by the package manager may not match the latest release of Asciidoctor.
Consult the package repository for your distribution to find out which version is packaged per distribution release.

* https://pkgs.alpinelinux.org/packages?name=asciidoctor[Alpine Linux (asciidoctor)]
* https://www.archlinux.org/packages/?name=asciidoctor[Arch Linux (asciidoctor)]
* https://packages.debian.org/sid/asciidoctor[Debian (asciidoctor)]
* https://apps.fedoraproject.org/packages/rubygem-asciidoctor[Fedora (asciidoctor)]
* https://software.opensuse.org/package/rubygem-asciidoctor[OpenSUSE (rubygem-asciidoctor)]
* https://packages.ubuntu.com/search?keywords=asciidoctor[Ubuntu (asciidoctor)]

If you want to use a version of Asciidoctor that is newer than what is installed by the package manager, see the <<gem-install,gem installation instructions>>.

However, some Linux distributions don't have the latest version of Asciidoctor packaged immediately after a new Asciidoctor gem is released.
If you need the latest version of Asciidoctor immediately, you'll have to use the `gem` command.
You'll also use the gem command to install a xref:gem.adoc#pre-release[pre-release version of Asciidoctor].
