// tag::indent[]
* The header in AsciiDoc is optional, but if
it is used it must start with a document title.

* Optional Author and Revision information
immediately follows the header title.

* The document header must be separated from
  the remainder of the document by one or more
  blank lines and cannot contain blank lines.
// end::indent[]

// tag::cont[]
* The header in AsciiDoc must start with a document title.
+
The header is optional.
// end::cont[]

// tag::complex[]
* The header in AsciiDoc must start with a document title.
+
----
= Document Title
----
+
Keep in mind that the header is optional.

* Optional Author and Revision information immediately follows the header title.
+
----
= Document Title
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
----
// end::complex[]


// tag::b-complex[]
* Every list item has at least one paragraph of content,
  which may be wrapped, even using a hanging indent.
+
Additional paragraphs or blocks are adjoined by putting
a list continuation on a line adjacent to both blocks.
+
list continuation:: a plus sign (`{plus}`) on a line by itself

* A literal paragraph does not require a list continuation.

 $ gem install asciidoctor

* AsciiDoc lists may contain any complex content.
+
[cols="2", options="header"]
|===
|Application
|Language

|AsciiDoc
|Python

|Asciidoctor
|Ruby
|===
// end::b-complex[]

// tag::complex-o[]
* The header in AsciiDoc must start with a document title.
+
--
Here's an example of a document title:

----
= Document Title
----

NOTE: The header is optional.

// end::complex-o[]

// tag::complex-only[]
. {blank}
+
----
print("one")
----
. {blank}
+
----
print("one")
----
// end::complex-only[]

// tag::complex-parent[]
* parent list item
** child list item

+
paragraph attached to parent list item
// end::complex-parent[]

// tag::complex-grandparent[]
* grandparent list item
** parent list item
*** child list item


+
paragraph attached to grandparent list item
// end::complex-grandparent[]

// tag::complex-enclosed[]
* grandparent list item
+
--
** parent list item
*** child list item
--
+
paragraph attached to grandparent list item
// end::complex-enclosed[]
