= Appendix Section Style
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// anchor um: user-appendix

The `appendix` section style can be used in books and articles, and it can have subsections.
While the AsciiDoc structure allows appendices to be placed anywhere, it's customary to place them near the end of the document.

== Appendix syntax

For articles, the appendix must be defined as a level 1 section (`==`).
For example:

[source]
----
include::{examplesdir}/appendix.adoc[tag=appx-article]
----

The table of contents will appear as follows:

----
include::{examplesdir}/appendix.adoc[tag=appx-article-out]
----

For books, the appendix must be defined as a level 1 section (`==`) if you want the appendix to be a adjacent to the chapters.
In a multi-part book, if you want the appendix to be adjacent to other parts, the appendix must be defined as a level 0 section (`=`).
In either case, the first subsection of the appendix must be a level 2 section (`===`).

The following example shows how to define an appendix for a multi-part book.

[source]
----
include::{examplesdir}/appendix.adoc[tag=appx-book]
----

The table of contents will appear as follows:

----
include::{examplesdir}/appendix.adoc[tag=appx-book-out]
----

[#caption]
== Appendix prefix

When rendered, the titles of sections marked as `appendix` will include:

* A prefix, taken from the value of the `appendix-caption` attribute, which defaults to "`Appendix`"
* A letter that represents the order of the appendix within the sequence of appendices (A, B, ...)
* A colon
* The section title

For example:

 Appendix A: Data Access Matrix

The prefix can be modified by setting the `appendix-caption` attribute and overriding the default value with a custom value.

[source]
----
:appendix-caption: Exhibit
----

Unset the attribute to remove the prefix.

[source]
----
:appendix-caption!:
----
