= Bibliography Section Style
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// biblio.adoc
// anchor from um: user-biblio

AsciiDoc has basic support for bibliographies.
While the structure of the bibliography entry is entirely freeform, AsciiDoc provides a way to reference the entries from the text and outputs the bibliography with proper semantics for processing by other toolchains (such as DocBook).

== Bibliography section syntax

To conform to output formats, a bibliography must be its own section.
The section must be assigned the `bibliography` section style.
The bibliography section is defined as a level 1 section (`==`) when:

* the doctype is `article`
* the doctype is `book` and the book doesn't contain any parts
* the bibliography is for a part

[source]
----
[bibliography]
== Bibliography
----

If the book has parts, and the bibliography is for the whole book, the section is defined as a level 0 section (`=`).

[source]
----
[bibliography]
= Bibliography
----

== Bibliography entries syntax

Bibliography entries are declared as items in an unordered list.

.Bibliography with references
[source]
----
include::{examplesdir}/bibliography.adoc[tag=base]
----

You can create an anchor for a bibliography entry by prefixing the entry with an ID enclosed in triple square brackets (`+[[[id]]]+`).
With this anchor, you can reference the entry from anywhere in the document using a cross reference (`+<<id>>+`).

|===
a|
include::{examplesdir}/bibliography.adoc[tag=base]
|===

By default, the reference to a bibliography entry is displayed as +[id]+.
If you specify reference text (xreftext) on the bibliography entry anchor (`+[[[id,xreftext]]]+`), a reference to the bibliography entry converts to +[xreftext]+.

If you want more advanced features such as automatic numbering and custom citation styles, try the {url-org}/asciidoctor-bibtex[asciidoctor-bibtex^] project.

//By adding the `bibliography` style to the section, you implicitly add it to each unordered list in that section.
//You promote a normal unordered list to a bibliography list by adding the `bibliography` style.
//WARNING: If the bibliography style is used on an unordered list outside of a bibliography section, the resulting behavior is undefined.
