= Section Levels and Titles
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
This is a new page extracted from sections.adoc.
The tag "intro" begins on that page, at "Sections partition the document into a content hierarchy." and ends on this page right before Titles as HTML headings.
////

== Section level syntax

A section title represents the heading for a section.
Section title levels are specified by two to six equal signs.
The number of equal signs in front of the title represents the nesting level (using a 0-based index) of the section.

.Section titles available in an article doctype
[source]
----
include::{examplesdir}/section.adoc[tag=base]
----

The section titles are rendered as:

include::{examplesdir}/section.adoc[tag=b-base]

Section levels must be nested logically.
There are two rules you must follow:

. A document can only have multiple level 0 sections if the `doctype` is set to `book`.
 ** The first level 0 section is the document title; subsequent level 0 sections represent parts.
. Section levels cannot be skipped when nesting sections (e.g., you can't nest a level 5 section directly inside a level 3 section; an intermediary level 4 section is required).

For example, the following syntax is illegal:

[source]
----
include::{examplesdir}/section.adoc[tag=bad]
----

Content above the first section title is designated as the document's preamble.
Once the first section title is reached, content is associated with the section it is nested in.

[source]
----
include::{examplesdir}/section.adoc[tag=content]
----

TIP: In addition to the equals sign marker used for defining section titles, Asciidoctor recognizes the hash symbol (`#`) from Markdown.
That means the outline of a Markdown document will be converted just fine as an AsciiDoc document.

== Titles as HTML headings
// tag::heading[]
When the document is converted to HTML 5 (using the built-in `html5` backend), each section title becomes a heading element where the heading level matches the number of equal signs.
For example, a level 1 section (`==`) maps to an `<h2>` element.
// end::heading[]

[#untitled]
== Hide special section titles

The titles of xref:special.adoc[special sections], such as the dedication, can be turned off by assigning `untitled` to the section's options attribute (`%` or `options=untitled`).
This feature is only available for the DocBook backend.

[source]
----
[dedication%untitled]
== Dedication

include::{examplesdir}/multi-special.adoc[tag=dedicate]
----
