= Sections
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
From sections.adoc, included in user-manual

The tag "intro" begins on this page, at "Sections partition the document into a content hierarchy." and ends on the levels-and-titles.adoc page right before Titles as HTML headings.
////

Sections partition the document into a content hierarchy.

With Asciidoctor you can:

* xref:level-and-title.adoc[Nest sections]
* xref:id.adoc[Control and assign section IDs, anchors, and linking]
* xref:number.adoc[Control and assign section numbering]
* xref:discrete.adoc[Create floating (discrete) sections]

== Section styles for technical content and books
// section-styles.adoc,

Asciidoctor provides xref:special.adoc[built-in styles] for the front matter and back matter sections commonly found in journal articles, academic papers, and books.
These special section styles are:

* Dedication
* Table of Contents
* Abstract
* Preface
* Part
* Chapter
* Appendix
* Glossary
* Bibliography
* Index
* Colophon

These styles are available to the `article` and `book` document types, with the exception of the part introduction style which is exclusive to books.
