= Processing Your Content
// partinro from Processing your content and all content from output-format.adoc and HTML
// output-format.adoc is included in convert-documents and the user-manual

While the AsciiDoc syntax is designed to be readable in raw form, the intended audience for that format are writers and editors.
Readers aren't going to appreciate the raw text nearly as much.
Aesthetics matter.
You'll want to apply nice typography with font sizes that adhere to the golden ratio, colors, icons and images to give it the respect it deserves.
That's where converters, backends, and themes come into play.

== Output formats

The Asciidoctor processor parses an AsciiDoc document and converts it to a variety of formats, such as HTML, DocBook, or PDF.

The processor generates the output format using a converter.
Each converter is mapped to the name of a backend.
You specify the backend--and, in turn, the converter--using the `-b` (`--backend`) command line option or `backend` API option.
If no backend is specified, the processor uses the converter for the default backend (`html5`).

Asciidoctor provides several built-in converters, which are mapped to the following backend names:

html (or html5)::
HTML 5, styled with CSS3 (default).

xhtml (or xhtml5)::
The XHTML variant of the output from `html5`.

docbook (or docbook5)::
DocBook 5.0 XML.0.

docbook45::
DocBook 4.5 XML.

manpage::
Manual pages for Unix and Unix-like operating systems.

Asciidoctor also has several add-on converters, which can be plugged in by adding the appropriate library to the runtime path (e.g., `-r asciidoctor-pdf`).
These converters are mapped to the following backend names:

pdf::
PDF, a portable document format.
Requires the https://rubygems.org/gems/asciidoctor-pdf[asciidoctor-pdf^] gem.

epub3::
EPUB3, a distribution and interchange format standard for digital publications and documents.
Requires the https://rubygems.org/gems/asciidoctor-epub3[asciidoctor-epub3^] gem.

latex::
LaTeX, a document preparation system for high-quality typesetting.
Requires the https://rubygems.org/gems/asciidoctor-latex[asciidoctor-latex^] gem.

mallard::
 Mallard 1.0 XML.
Requires the https://github.com/asciidoctor/asciidoctor-mallard[asciidoctor-mallard^] gem (not yet released).

== HTML slide decks
// directly from um

In addition to generating normal documents from AsciiDoc (e.g., a book or article), you can also use AsciiDoc to create HTML-based slide decks.
The converters for creating HTML-based slides add some additional structure rules to the document for defining slides.
However, nothing in this structure restricts you from still being able to publish the content as a normal document too.

The conversion from AsciiDoc to an HTML-based slide deck is handled by one of the following converters from the Asciidoctor ecosystem:

* https://github.com/asciidoctor/asciidoctor-reveal.js[Asciidoctor Reveal.js^] -- Converts an AsciiDoc document into a Reveal.js presentation
* https://github.com/asciidoctor/asciidoctor-bespoke[Asciidoctor Bespoke^] -- Converts an AsciiDoc document into a Bespoke presentation

There's also a converter for making deck.js slide decks, but we discourage using it as deck.js itself is very outdated.



// TODO describe the role of template converters (e.g., asciidoctor-backends)

////
Pulled directly from the user manual - need to decide where this information goes and how it should be presented.

== PDFs

Conversion from AsciiDoc to PDF is made possible by a number of tools.

{uri-asciidoctor-pdf}[Asciidoctor PDF]::
A native PDF converter for Asciidoctor (converts directly from AsciiDoc to PDF using Prawn).
+
Instructions for installing and using Asciidoctor PDF are documented in the project's {uri-asciidoctor-pdf-readme}[README].
The tool provides built-in theming via a YAML configuration file, which is documented in the {uri-asciidoctor-pdf-theming-guide}[theming guide].
+
TIP: Asciidoctor PDF is the preferred tool for converting to PDF and is fully supported by the Asciidoctor community.

a2x::
A DocBook toolchain frontend provided by that AsciiDoc Python project.
+
To use this tool, you should first convert to DocBook using Asciidoctor, then convert the DocBook to PDF using a2x.
a2x accepts a DocBook file as input and can convert it to a PDF using either Apache FOP or dblatex.
Instructions for using a2x are documented in the project's {uri-a2x-manpage}[man page].

{fopub-ref}[asciidoctor-fopub]::
A DocBook toolchain frontend similar to a2x, but which only requires Java to be installed on your machine.
+
Instructions for using asciidoctor-fopub are documented in the project's {fopub-doc-ref}[README].
To alter the look and feel of the PDF, it's necessary to pass XSL parameters or modify the XSLT.
More information about customization can be found in http://www.sagehill.net/docbookxsl/[DocBook XSL: The Complete Guide].
////
