.TH "block verse" 1
." URL portability
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
." Bug fix
.ie \n\(.g .ds Aq \(aq
.el       .ds Aq '
." Disable hiphenation
.nh
." Disable justification
.ad l
.SH "NAME"
block verse \- test
.SH "TESTS"
." .basic


.in +.5i
.ll -.5i
.nf
The fog comes
on little cat feet.
.fi
.br
.in
.ll

." .basic_with_attribution


.in +.5i
.ll -.5i
.nf
The fog comes
on little cat feet.
.fi
.br
.in
.ll
.in +.3i
.ll -.3i
\(em Carl Sandburg
.in
.ll

." .basic_with_attribution_and_citetitle


.in +.5i
.ll -.5i
.nf
The fog comes
on little cat feet.
.fi
.br
.in
.ll
.in +.3i
.ll -.3i
two lines from the poem Fog \(em Carl Sandburg
.in
.ll

." .basic_with_title

.in +.3i
\fBPoetry\fR
.br
.in
.in +.5i
.ll -.5i
.nf
The fog comes
on little cat feet.
.fi
.br
.in
.ll

." .basic_with_id_and_role


.in +.5i
.ll -.5i
.nf
The fog comes
on little cat feet.
.fi
.br
.in
.ll

." .block


.in +.5i
.ll -.5i
.nf
The fog comes
on little cat feet.

It sits looking
over harbor and city
on silent haunches
and then moves on.
.fi
.br
.in
.ll
