." URL portability
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH "inline anchor" 1

." .basic
.sp

.URL "http://www.asciidoctor.org" "http://www.asciidoctor.org"

." .basic_with_text
.sp

.URL "irc://irc.freenode.org/#asciidoctor" "Asciidoctor IRC channel"

." .basic_with_target_blank
.sp

.URL "view\-source:asciidoctor.org" "Asciidoctor homepage"

." .basic_with_role
.sp

.URL "http://discuss.asciidoctor.org/" "\fBmailing list\fR"

." .xref
.sp
The section 
.URL "#page\-break" "[page\-break]"
 describes how to add a page break.

." .xref_with_text
.sp
The section 
.URL "#page\-break" "Page break"
 describes how to add a page break.

." .xref_resolved_text
.sp
Refer to 
.URL "#_section_a" "Section A"
\&.

.SH "Section A"


." .bibref
.sp

.URL "prag"
 Andy Hunt &amp; Dave Thomas. The Pragmatic Programmer
