.TH "Inline image" 1
." URL portability
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac

." .image
.sp
\fB[linux]\fR

." .image_with_alt_text
.sp
\fB[Tux]\fR

." .image_with_dimensions
.sp
\fB[Tux]\fR

." .image_with_float
.sp
\fB[linux]\fR

." .image_with_link
.sp

.URL "http://inkscape.org/doc/examples/tux.svg" "linux"

." .image_with_role
.sp
\fB[linux]\fR

." .icon
.sp
\fB[tags]\fR

." .icon_with_dimensions
.sp
\fB[tags]\fR

." .icon_with_float
.sp
\fB[heart]\fR

." .icon_with_link
.sp

.URL "http://rubygems.org/downloads/asciidoctor\-1.5.2.gem" "download"

." .icon_with_title
.sp
\fB[heart > I <3 Asciidoctor]\fR

." .icon_with_role
.sp
\fB[tags]\fR

." .icon_no_icons
.sp
\fB[tags]\fR
