= Quote and Excerpt Blocks
:url-air: http://en.wikipedia.org/wiki/Air_quotes
// quote-alt.adoc, included in user-manual: quote: Quoted paragraph

== Basic quote syntax

// tag::basic[]
For content that doesn't require the preservation of line breaks, set the `quote` attribute in the first position of the attribute list.
Next, set the attribution and relevant citation information.
However, these positional attributes are optional.

.Anatomy of a basic quote
----
[quote, attribution, citation title and information]
Quote or excerpt text
----

If the quote is a single line or paragraph, you can place the attribute list directly on top of the text.

.Quote paragraph syntax
[source]
----
include::{examplesdir}/quote.adoc[tag=para2-c]
----
<1> Mark lead-in text explaining the context or setting of the quote using a period (`.`). (optional)
<2> For content that doesn't require the preservation of line breaks, set `quote` in the first position of the attribute list.
<3> The second position contains who the excerpt is attributed to. (optional)
<4> Enter additional citation information in the third position. (optional)
<5> Enter the excerpt or quote text on the line immediately following the attribute list.

.Result: Quote paragraph
====
include::{examplesdir}/quote.adoc[tag=para2]
====

== Quoted block

If the quote or excerpt is more than one paragraph, place the text between delimiter lines consisting of four underscores (`+____+`).

.Quote block syntax
[source]
----
include::{examplesdir}/quote.adoc[tag=comp]
----

.Result: Quote block
====
include::{examplesdir}/quote.adoc[tag=comp]
====

Asciidoctor also provides three alternative ways to markup quotes and prose excerpts.
// end::basic[]

== Quoted paragraph

You can turn a single paragraph into a blockquote by:

. surrounding it with double quotes
. adding an optional attribution (prefixed with two dashes) below the quoted text

.Quoted paragraph syntax
[source]
----
include::{examplesdir}/quote.adoc[tag=abbr]
----

.Result: Quoted paragraph
====
include::{examplesdir}/quote.adoc[tag=abbr]
====

=== Air quotes

{url-air}[Air quotes^] are two double quotes on each line, emulating the gesture of making quote marks with two fingers on each hand.

[source]
----
include::{examplesdir}/quote.adoc[tag=air]
----

.Result: Air quotes
====
include::{examplesdir}/quote.adoc[tag=air]
====

=== Markdown-style blockquotes

Asciidoctor supports Markdown-style blockquotes.

.Markdown-style blockquote syntax
[source,markdown]
----
include::{examplesdir}/quote.adoc[tag=md]
----

.Result: Markdown-style blockquote
====
include::{examplesdir}/quote.adoc[tag=md]
====

Like Markdown, Asciidoctor supports block content inside the blockquote, including nested blockquotes.

[source,markdown]
.Markdown-style blockquote containing block content
....
include::{examplesdir}/quote.adoc[tag=md-alt]
....

Here's how this conversation renders.

.Result: Markdown-style blockquote with block content
====
include::{examplesdir}/quote.adoc[tag=md-alt]
====
