= A Book with Multiple Parts and Special Sections

[colophon]
= Colophon
// tag::colophon[]
The Asciidoctor Press, Ceres and Denver.

(C) 2018 by The Asciidoctor Press

Published in the Milky Way Galaxy.

This book is designed by Dagger Flush, Denver, Colorado.
The types are handset Volcano Dust and Papaya, designed by Leeloo.
Leeloo created the typefaces to soften the bluntness of documentation.

Built with Asciidoctor on Fedora 28.

Printing and binding by Ceres Lithographing, Inc., Ceres, Milky Way.
// end::colophon[]

[preface]
= Preface

I awoke one morning and was confronted by the dark and stormy eyes of the chinchilla.
She had conquered the mountain of government reports that had eroded into several minor foothills and a creeping alluvial plain of loose papers.

=== Preface Subsection

Chinchillas rule the world.

= Dedication
// tag::dedicate[]
For S.S.T.--

thank you for the plague of archetypes.
// end::dedicate[]

// tag::part[]
= Book Title
:doctype: book

[preface]
= Forward

This is the preface for the whole book.

= Part 1

This is the introduction to the first part of our mud-encrusted journey.

== Chapter 1

There was mud...

== Chapter 2

Great gobs of mud...

[glossary]
== Part 1 Glossary

[glossary]
mud:: wet, cold dirt

= Part 2

[preface]
== Part 2 Preface

This is a preface for part 2.

== Chapter 3

The mud had turned to cement...

// end::part[]

= Appendix for whole Book

=== Appendix sub
