= Literal Blocks
// literal.adoc, included in user-manual: Literal Text and Blocks

Literal blocks display the text you write exactly as you enter it.
Literal text is treated as preformatted text.
The text is shown in a fixed-width font and endlines are preserved.
Only xref:subs:special-characters.adoc[special characters] and callouts are replaced when the document is converted.

== Literal syntax

Literal blocks are defined three ways:

. Indenting the first line of a paragraph by one or more spaces
. Applying the `literal` attribute to a paragraph or block
. Using the literal block delimiter (`\....` )

=== Implicit indent method

When a line begins with one or more spaces it is displayed as a literal block.
This method is a quick and easy way to insert code snippets.

.Implicit literal text
[source]
----
include::{examplesdir}/literal.adoc[tag=imp]
----

.Result: Implicit literal text
include::{examplesdir}/literal.adoc[tag=imp]

=== Literal style

When you want an entire block of text to be literal and would prefer not to indent it, set the `literal` attribute on top of the element.

.Literal style syntax
[source]
----
include::{examplesdir}/literal.adoc[tag=para]
----

.Result: Literal style
include::{examplesdir}/literal.adoc[tag=para]

=== Delimited literal block

Finally, you can surround the content you want rendered as literal by enclosing it in a set of literal block delimiters (`\....`).
This method is useful when the content consists of several elements that are separated by blank lines.

.Literal delimited block syntax
[source]
----
include::{examplesdir}/literal.adoc[tag=block]
----

Notice in the output that the bold text formatting is not applied to the text nor are the three consecutive periods replaced by the ellipsis Unicode character.

.Result: Literal delimited block
include::{examplesdir}/literal.adoc[tag=block]
