= Source Code Blocks
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: source code snippets
////
From src.adoc, included in:
- user-manual: Syntax Highlighting Source Code

From user manual:
NOTE we really want this ID on the section, but there are problems w/ multiple IDs per section
[#source-code-blocks]
[#syntax-highlighting]
////

Developers are accustomed to seeing source code that uses color and other styling to emphasize the code's structure (i.e., keywords, types, delimiters, etc.).
This technique is known as [.term]_syntax highlighting_ source code (or [.term]_source highlighting_, for short).
Since this technique is so prevalent--one could say expected--Asciidoctor integrates a wealth of libraries to syntax highlight source code blocks in your document.
This list includes CodeRay, Pygments, highlight.js, and prettify.

== Enabling source highlighting

When enabled, syntax highlighting gets applied to listing or literal blocks that have the `source` block style and a source language.
However, syntax highlighting is _not_ enabled by default.

To enable syntax highlighting in a document, you must set the `source-highlighter` document attribute.
You can set this attribute in the document or from the CLI or API.

//Some source highlighters, such as CodeRay and Pygments, require an additional library to be installed.
//Others, like highlight.js and prettify, load the library at runtime from a CDN or from a custom URL or file path.

If you set the attribute in the document, it _must_ be defined in the #document header#.

[source]
----
= Document Title
:source-highlighter: <value>
----

For example, here's how to enable syntax highlighting using CodeRay:

[source]
----
= Document Title
:source-highlighter: coderay
----

== Available source highlighters

The following table lists the recognized values for the `source-highlighter` attribute.

.Recognized values and supported environments for the `source-highlighter` attribute
[cols="1,1m,2"]
|===
|Library Name |Attribute Value |Supported Environments

|{url-coderay}[CodeRay^]
|coderay
|Asciidoctor, AsciidoctorJ, Asciidoctor PDF

|{url-highlightjs}[highlight.js^]
|highlightjs
|Asciidoctor, AsciidoctorJ, Asciidoctor.js

|{url-prettify}[prettify^]
|prettify
|Asciidoctor, AsciidoctorJ, Asciidoctor.js

|{url-pygments}[Pygments^]
|pygments
|Asciidoctor, Asciidoctor PDF

|{url-rouge}[Rouge^]
|rouge
|Asciidoctor PDF
|===

[IMPORTANT]
====
To use CodeRay, Pygments, or Rouge, you must have the appropriate library installed on your system.
See xref:coderay.adoc[CodeRay] or xref:pygments.adoc[Pygments] to find installation instructions.
(We don't yet have a section about Rouge).

On the other hand, if you're using a client-side syntax highlighting library like highlight.js or prettify, there's no need to install additional libraries.
The generated HTML will load the required source files from a CDN (or custom URL or file path).
====

== Applying source highlighting

To apply highlighting to source code, you must add the `source` block style to a listing block, literal block, or paragraph and also specify a source language.

[listing]
.Code block with title and syntax highlighting
....
include::{examplesdir}/source.adoc[tag=src-base-co]
....
<1> An optional title can be added to the block.
<2> An optional ID can be added to the block.
<3> Assign the block name `source` to the first position in the attribute list.
<4> Assign a source language to the second position.
<5> The source block name is typically assigned to listing and literal blocks.

.Result: Source block with title and syntax highlighting
====
include::{examplesdir}/source.adoc[tag=src-base-co-res]
====

.Source style
[source]
----
include::{examplesdir}/source.adoc[tag=src-para-co]
----
<1> Place the attribute list directly on the paragraph
<2> Once an empty line is encountered the syntax highlighting is unset.

.Result: Source style
====
include::{examplesdir}/source.adoc[tag=src-para]
====

If the majority of your source blocks use the same source language, you can set the `source-language` attribute in the document header and assign a language to it.

[listing]
.Source language attribute
....
include::{examplesdir}/source.adoc[tag=src-lang]
....

Additionally, you can use an xref:directives:include-directive.adoc[include directive] to insert source code into an AsciiDoc document directly from a file.

[listing]
.Code block inserted from another file
....
include::{examplesdir}/source.adoc[tag=src-inc]
....

//TODO mention the use of AsciiDoc tags to include code snippets and the indent flag to reset indentation

TIP: If you specify custom substitutions on the source block using the `subs` attribute, make sure to include the `specialcharacters` substitution if you want to preserve syntax highlighting.
However, if you do plan to modify the substitutions, we recommend using xref:subs:apply.adoc#incremental[incremental substitutions] instead.

// Highlight PHP sidebar was taken from end of page and made its own page
