= Docinfo Processor

DocinfoProcessor is a DocumentProcessor

== DSL methods

include::page$processor.adoc[tag=docproc]

`at_location`::
When called with `footer`, the supplied content will be added to the footer of the document.

NOTE: The default location is `:head`.
The recognized values for html5 are `:head` and `:footer`.
The recognized values for docbook5 are `:header` and `:footer`.

== Process method

`def process document`

The process method is called from a converter.
Therefore document attributes are available and the block structure of the document is available.

The `process` method should return the text to be added to the specified location as a string.

== Example

Purpose::
Appends the Google Analytics tracking code to the bottom of an HTML document.

== GoogleAnalyticsDocinfoProcessor

[source,ruby]
----
class GoogleAnalyticsDocinfoProcessor < Asciidoctor::Extensions::DocinfoProcessor
  enable_dsl
  at_location :footer
  def process document
    return unless (ga_account_id = document.attr 'google-analytics-account')
    %(<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create','#{ga_account_id}','auto');
ga('send','pageview');
</script>)
  end
end
----

== Usage

[source,ruby]
----
Asciidoctor::Extensions.register do
  docinfo_processor GoogleAnalyticsDocinfoProcessor
end

Asciidoctor.convert_file 'sample.adoc', safe: :safe, attributes: 'UA-ABCXYZ123'
----
