:uri-named-arguments: https://www.regular-expressions.info/named.html
= Inline Macro Processor

InlineMacroProcessor is a SyntaxProcessor

Note:
Currently, uses of inline macros are recognized and processed during the conversion phase of a parsed block.
Furthermore, uses are recognized by means of a regular expression.
One of the goals of many participating the in Asciidoc language standardization effort is to sufficiently define the language so that inline macro uses can be recognized and processed during the parse phase, so the inline Nodes returned from processing form part of the DOM or parse tree.
This will certainly affect the state of the document visible to inline macros and may affect how uses are recognized, the input to the process method, and the expected contents of the inline nodes produced.
See https://github.com/asciidoctor/asciidoctor/issues/61[].
When this occurs it is possible that inline macros will have to be rewritten.
Most likely an adapter will be provided to adapt the inputs and outputs, but an inline macro that depends on being able to examine the entire tree of blocks from the parse step is unlikely to be able to work.

== Registration method

An InlineMacroProcessor is registered with `inline_macro`.

== DSL methods

include::page$processor.adoc[tag=syntaxproc]

`format`::
When called with `short`, the inline macro will have no target, e.g. `mymacro:[attributes]`.

`match`::
Supplies a regexp to match the inline macro use.
This overrides `format` as `format` uses `short` to set a particular regexp.
+
Regexp {uri-named-arguments}[named capturing groups] can be used, but only the defined names `target` and `content` are allowed.
+
Use of this argument allows macros with a form defined by a regular expression.
This allows them to match any naming convention in a document.
One use for this would be automatically linking to standards as shown in the example below.

== Process method

`def process parent, target, attributes`

* parent is the enclosing block or document.
* target is the text between the `name::` and `[...]`.
Target is missing for a `short` format macro.
* attributes is a hash of the contents of `[...]` interpreted using positional_attributes and combined with default attributes.

The process method should return an `InlineNode` containing the desired content.

== Example with name::[] form

Purpose::
Create an inline macro named `man` that links to a manpage.

=== sample-with-man-link.adoc

[source,asciidoc]
----
See man:gittutorial[7] to get started.
----

=== ManpageInlineMacro

[source,ruby]
----
require 'asciidoctor'
require 'asciidoctor/extensions'

class ManInlineMacro < Asciidoctor::Extensions::InlineMacroProcessor
  enable_dsl

  named :man
  name_positional_attributes 'volnum'

  def process parent, target, attrs
    text = manname = target
    suffix = ''
    target = %(#{manname}.html)
    suffix = if (volnum = attrs['volnum'])
      "(#{volnum})"
    else
      nil
    end
    parent.document.register :links, target
    create_anchor parent, text, type: :link, target: %(#{target}#{suffix})
  end
end
----

=== Usage

[source,ruby]
----
Asciidoctor::Extensions.register do
  inline_macro ManInlineMacro
end

Asciidoctor.convert_file 'sample-with-man-link.adoc', safe: :safe
----

== Example with regular expression form

Purpose::
Create an inline macro to identify use of RFC standards in Asciidoc source and automatically provide hyperlinks to the document.

=== RFCStandardLinkInlineMacro

[source,ruby]
----
include::example$rfc-link-extension-inline.rb[tag=extension]
----

=== Usage

[source, ruby]
----
include::example$rfc-link-extension-inline.rb[tag=usage]
----

=== Example output

[source,html]
----
<div class="paragraph">
<p>Check out for example <a href="https://tools.ietf.org/html/1882">1882</a> at Christmas, <a href="https://tools.ietf.org/html/1927">1927</a> when I forget the space.
Not to mention <a href="https://tools.ietf.org/html/2549">2549</a>, a personal favorite.</p>
</div>
----