= Inline Macro Processor

InlineMacroProcessor is a SyntaxProcessor

== DSL methods

include::page$processor.adoc[tag=syntaxproc]

`format`::
When called with `short`, the inline macro will have no target, e.g. `mymacro:[attributes]`.

`match`::
Supplies a regexp to match the inline macro use.
This overrides `format` as `format` uses `short` to set a particular regexp.

== Process method

`def process parent, target, attributes`

* parent is the enclosing block or document.
* target is the text between the `name::` and `[...]`.
Target is missing for a `short` format macro.
* attributes is a hash of the contents of `[...]` interpreted using positional_attributes and combined with default attributes.

The process method should return an `InlineNode` containing the desired content.

== Example

Purpose::
Create an inline macro named `man` that links to a manpage.

== sample-with-man-link.adoc

[source,asciidoc]
----
See man:gittutorial[7] to get started.
----

== ManpageInlineMacro

[source,ruby]
----
require 'asciidoctor'
require 'asciidoctor/extensions'

class ManInlineMacro < Asciidoctor::Extensions::InlineMacroProcessor
  enable_dsl

  named :man
  name_positional_attributes 'volnum'

  def process parent, target, attrs
    text = manname = target
    suffix = ''
    target = %(#{manname}.html)
    suffix = if (volnum = attrs['volnum'])
      "(#{volnum})"
    else
      nil
    end
    parent.document.register :links, target
    create_anchor parent, text, type: :link, target: %(#{target}#{suffix})
  end
end
----

== Usage

[source,ruby]
----
Asciidoctor::Extensions.register do
  inline_macro ManInlineMacro
end

Asciidoctor.convert_file 'sample-with-man-link.adoc', safe: :safe
----
