= Preprocessor

Preprocessor is a DocumentProcessor

== Registration method

A Preprocessor is registered with `preprocessor`.

== DSL methods

include::page$processor.adoc[tag=docproc]

== Process method

`def process document, reader`

The process method is called from a Document.
The document has not yet been parsed.
The reader is positioned at the "start" of the document, which may be the actual beginning of the source available to the Reader or a position advanced by a preceding Preprocessor.
Depending on the circumstances, the reader may be the reader originally created to read the source for the document or a reader from a preceding Preprocessor.

The `process` method should a Reader or nil.
The returned reader can be an entirely new Reader or the original reader, perhaps advanced, as in the example.

== Example

Purpose::
Skim off, from the top of the document, front matter that gets used by site generators such as Jekyll and Awestruct.

== sample-with-front-matter.adoc

[source,asciidoc]
----
tags: [announcement, website]
---
= Document Title

content

[subs=+attributes]
.Captured front matter
....
---
{front-matter}
---
....
----

== FrontMatterPreprocessor

[source,ruby]
----
require 'asciidoctor'
require 'asciidoctor/extensions'

class FrontMatterPreprocessor < Asciidoctor::Extensions::Preprocessor
  def process document, reader
    lines = reader.lines # get raw lines
    return reader if lines.empty?
    front_matter = []
    if lines.first.chomp == '---'
      original_lines = lines.dup
      lines.shift
      while !lines.empty? && lines.first.chomp != '---'
        front_matter << lines.shift
      end

      if (first = lines.first).nil? || first.chomp != '---'
        lines = original_lines
      else
        lines.shift
        document.attributes['front-matter'] = front_matter.join.chomp
        # advance the reader by the number of lines taken
        (front_matter.length + 2).times { reader.advance }
      end
    end
    reader
  end
end
----

== Usage

[source,ruby]
----
Asciidoctor::Extensions.register do
  preprocessor FrontMatterPreprocessor
end

Asciidoctor.convert_file 'sample-with-front-matter.adoc', safe: :safe
----
