= Preprocessor

Preprocessor is a DocumentProcessor

== Registration method

A Preprocessor is registered with `preprocessor`.

== DSL methods

include::page$processor.adoc[tag=docproc]

== Process method

`def process document, reader`

The process method is called from a Document.
The document has not yet been parsed.
The reader is positioned at the "start" of the document, which may be the actual beginning of the source available to the Reader or a position advanced by a preceding Preprocessor.
Depending on the circumstances, the reader may be the reader originally created to read the source for the document or a reader from a preceding Preprocessor.

The `process` method should a Reader or nil.
The returned reader can be an entirely new Reader or the original reader, perhaps advanced, as in the example.

== Example

Purpose::
Skim off, from the top of the document, front matter that gets used by site generators such as Jekyll and Awestruct.

=== FrontMatterPreprocessor

[source,ruby]
----
include::example$pre-front-matter-extension.rb[]
----

=== Usage

[source,ruby]
------
include::example$pre-front-matter-extension-runner.sh[tag=runner]
------

=== Output

[source,html]
----
include::example$pre-front-matter-extension-out.html[]
----
