= Tree Processor

TreeProcessor is a DocumentProcessor

== Registration method

A TreeProcessor is registered with `tree_processor`.

== DSL methods

include::page$processor.adoc[tag=docproc]

== Process method

`def process document`

The process method is called from a Document after parsing.
Therefore document attributes are available and the block structure of the document is available.

The `process` method may modify the document and return the document or nil, or return a new Document.
The document attributes are reset to the header attributes before the first tree processor is called.
A tree processor should thus assure that the attributes of the original or returned document are reset to the header attributes by calling `document.restore_attributes` if the attributes have been modified.

There are two basic strategies for a TreeProcessor.

=== Query the document blocks using the `document.find_by` method

This provides quick simple access to the blocks of interest, but does not provide access to the attributes set in the document after the document header.
Only the header attributes are available.

A block found this way can be replaced with `parent.blocks[parent.blocks.index original_block] = new_block`.

=== Traverse the block tree

The code here is more complicated and needs to be recursive to find all blocks, but the attributes present at each block may be computed as the traversal proceeds.
To replay the attributes, for each block execute `document.playback_attributes block.attributes`.
Remember to call `document.restore_attributes` before returning.

== Example

Purpose::
Detect literal blocks that contain shell commands, strip the prompt character and style the command using CSS in such a way that the prompt character cannot be selected (as seen on help.github.com).

== sample-with-shell-session.adoc

[source,asciidoc]
----
 $ echo "Hello, World!"
 > Hello, World!

 $ gem install asciidoctor
----

== ShellSessionTreeProcessor

[source,ruby]
----
class ShellSessionTreeProcessor < Asciidoctor::Extensions::TreeProcessor
  def process document
    return unless document.blocks?
    process_blocks document
    nil
  end

  def process_blocks node
    node.blocks.each_with_index do |block, i|
      if block.context == :literal &&
          (((first_line = block.lines.first).start_with? '$ ') ||
            (first_line.start_with? '> '))
        node.blocks[i] = convert_to_terminal_listing block
      else
        process_blocks block if block.blocks?
      end
    end
  end

  def convert_to_terminal_listing block
    attrs = block.attributes
    attrs['role'] = 'terminal'
    prompt_attr = (attrs.has_key? 'prompt') ?
        %( data-prompt="#{block.sub_specialchars attrs['prompt']}") : nil
    lines = block.lines.map do |line|
      line = block.sub_specialchars line.chomp
      if line.start_with? '$ '
        %(<span class="command"#{prompt_attr}>#{line[2..-1]}</span>)
      elsif line.start_with? '&gt; '
        %(<span class="output">#{line[5..-1]}</span>)
      else
        line
      end
    end
    create_listing_block block.document, lines * EOL, attrs, subs: nil
  end
end
----

== Usage

[source,ruby]
----
Asciidoctor::Extensions.register do
  tree_processor ShellSessionTreeProcessor
end

Asciidoctor.convert_file 'sample-with-shell-session.adoc', safe: :safe
----

////
In the example below the TreeProcessor examines the block contents looking for the `// (*)` suffix and rewrites the line so that Asciidoctor formats it appropriately.

[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
            .antMatchers("/resources/**").permitAll() // (*)
            .anyRequest().authenticated()
            .and()
        .formLogin()
            .loginPage("/login")
            .permitAll();
----
////
