= Install and Update

To simplify installation, Asciidoctor is packaged and distributed as a {url-rubygem}/asciidoctor[RubyGem to the package repository at RubyGems.org^].
It's also distributed as a package for popular Linux distributions and macOS.
In addition to running on Ruby, Asciidoctor can be executed on a JVM using xref:asciidoctorj::index.adoc[AsciidoctorJ] or in any JavaScript environment (including the browser) using xref:asciidoctor.js::index.adoc[Asciidoctor.js].

== Installation methods

Asciidoctor can be installed using:

* package managers for popular Linux distributions,
* Homebrew for macOS,
* the `gem install` command (recommended for Windows users or if you'll be installing additional gems),
* the Asciidoctor Docker image, or
* Bundler.

The benefit of using your operating system's package manager to install the gem is that it handles installing Ruby and the RubyGems library if those packages are not already installed on your machine.

You should use the same method to update Asciidoctor as you use to install it.
