= Horizontal Rules and Page Breaks
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
hr.adoc, included in:
- user-manual: Horizontal Rules
////

== Horizontal rules

.Horizontal rule syntax
[source]
----
include::{partialsdir}/ex-hr.adoc[tag=base]
----

.Result: Horizontal rule
--
include::{partialsdir}/ex-hr.adoc[tag=base]
--

=== Markdown-style horizontal rules

Asciidoctor recognizes Markdown horizontal rules.
The motivation here is to ease migration of Markdown documents to AsciiDoc documents.

To avoid conflicts with AsciiDoc's block delimiter syntax, only 3 repeating characters (`-` or `+*+`) are recognized.
As with Markdown, whitespace between the characters is optional.

.Markdown-style horizontal rule syntax
[source,markdown]
----
include::{partialsdir}/ex-hr.adoc[tag=md]
----

.Result: Markdown-style horizontal rules
--
include::{partialsdir}/ex-hr.adoc[tag=md]
--

A macro definition for the Markdown horizontal rules is included in the AsciiDoc compatibility file so they can be recognized by the `asciidoc` command as well.

== Page Breaks
// from page-break.adoc

.Page break syntax
[source]
----
<<<
----
