= Section Numbers
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// New page, content taken from sections.adoc

== Numbering

// tag::number[]
Asciidoctor allows section numbering to be toggled on and off throughout a document.
You can enable section numbers using the `sectnums` attribute.

[source]
----
:sectnums:
----

NOTE: Asciidoctor still supports the attribute name `numbered` to number sections for backward compatibility with AsciiDoc Python, but the name `sectnums` is preferred.

You can also use this attribute entry above any section title in the document to toggle the auto-numbering setting.
When you want to turn off the numbering, add an exclamation point to the end of the attribute name:

[source]
----
include::{examplesdir}/section.adoc[tag=num-off]
----

For regions of the document where section numbering is turned off, the section numbering will not be incremented.

Given:

[source]
----
include::{examplesdir}/section.adoc[tag=num]
----

The sections will be numbered as follows:

[source]
----
include::{examplesdir}/section.adoc[tag=num-out]
----

Asciidoctor will always curtail incrementing the section number in regions of the document where section numbers are off.

If `sectnums` is set on the command line (or API), that overrides the value set in the document header, but it does not prevent the document from toggling the value for regions of the document.

If `sectnums!` is set on the command line (or API), then the numbers are disabled regardless of the setting within the document.

.Flexible attributes
NOTE: The `sectnums` attribute is referred to as a "`flexible attribute`", which means it can always be changed midstream in the document, even if it is enabled through the API or CLI.
At the time of writing, `sectnums` is unique in this way, though other attributes may receive this special status in the future.

== Numbering depth

You can restrict section numbering depth by defining the `sectnumlevels` (document header-only) attribute.

[source]
----
include::{examplesdir}/section.adoc[tag=sectnuml]
----
<1> When the `sectnumlevels` attribute is assigned a value of `2`, section titles with levels 3 through 5 are not numbered (i.e., not prefixed with a number).

Assigning `sectnumlevels` a value of `0` is effectively the same as disabling section numbering (i.e., `sectnums!`).
// end::number[]
