= Parts and Chapters
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
from file book-parts.adoc
anchor from user manual: book-parts-and-chapters
Included in:
- user-manual
////

You may group the sections of your document into parts when you set the `doctype` to `book`.
In fact, parts can only be used when the `doctype` is `book`.

When a document has its `doctype` set to `book` and contains at least one part, it implicitly becomes a multi-part book.
There is no dedicated doctype value for a multi-part book to distinguish it from a regular book.
That distinction is made by the content.

== Part titles and introductions

Part titles are specified with a single equals sign (`=`), the equivalent to the structure of a document title (i.e., level-0 section).
Each part must contain at least one section (a chapter or special section).
Immediately after the part title, you may insert an optional introduction, which is designated by the `partintro` style.

[source]
----
[partintro]
.Optional part introduction title
--
Optional part introduction goes here.
--
----

A part can also include its own preface, bibliography, glossary and index.

[source]
----
include::{partialsdir}/multi-special-ex.adoc[tag=part]
----

== Chapter titles and labels

When using the PDF converter (i.e., Asciidoctor PDF), the value of the `chapter-label` attribute (followed by a space) is automatically added to the beginning of the chapter title.
A chapter title is a level-1 section title when the doctype is book.

You can modify this prefix by redefining the `chapter-label` attribute.

[source]
----
:chapter-label: Chapter ~
----

To use no prefix, set the value to blank.
