= Sections
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
////
From sections.adoc, included in:
- user-manual

The tag "intro" begins on this page, at "Sections partition the document into a content hierarchy." and ends on the levels-and-titles.adoc page right before Titles as HTML headings.
////

Sections partition the document into a content hierarchy.

With Asciidoctor you can:

* xref:levels-and-titles.adoc[Nest sections]
* xref:ids.adoc[Control and assign section IDs, anchors, and linking]
* xref:numbers.adoc[Control and assign section numbering]
* xref:discrete.adoc[Create floating (discrete) sections]

== Section styles for technical content and books
////
This is the content for section-styles.adoc, included in:
- user-manual: sections: section styles
////

Asciidoctor provides styles for the frontmatter and backmatter sections commonly found in journal articles, academic papers, and books.
The styles are:

* colophon
* abstract
* preface
* dedication
* part introduction
* appendix
* glossary
* bibliography
* index

These styles are available to the `article` and `book` document types, with the exception of the part introduction style which is exclusive to books.
The structure and usage rules for each section style is explained in the xref:book:structure.adoc[Book documentation].

////
In general, the section style attribute is set above a level 1 section title or block of text.
For instance, the example below shows how to label a section as an abstract.

[source]
----
[abstract]
== Documentation Abstract

Documentation is a distillation of many long, squiggly adventures.
----
////
